version: "3"
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

  app:
    image: biby05/galleryapp
    container_name: galleryapp
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/gallerydb
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
