version: "3"
services:
  mongo:
    image: mongo
    container_name: galleryapp_mongo
    ports:
      - "27017:27017"
    restart: always

  galleryapp:
    image: biby05/galleryapp:latest
    container_name: galleryapp
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/galleryapp
